name: final-project-pt1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - numpy=1.24
  - pandas=1.5.3
  - matplotlib
  - seaborn
  - pip
  - pip:
      - pyjanitor
      - nfl_data_py

